### ISSUE TITLE
Manual build failing

### ISSUE THREAD

**Issue by MattAtkinson** [armPelionEdge/manifest-pelion-edge#18]
I tried following the manual steps process on an Ubuntu 18.04 VM running on a Windows machine. It seems to get all the way through the build process until it fails on just one component:

```
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: libpng-native-1.6.36-r0 do_fetch: Failed to fetch URL http://downloads.sourceforge.net/project/libpng/libpng16/1.6.36/libpng-1.6.36.tar.xz, attempting MIRRORS if available
ERROR: nodejs-8.11.2-r1.1 do_package: Fatal errors occurred in subprocesses:
Command '['arm-poky-linux-gnueabi-objcopy', '--only-keep-debug', '/home/matt/build/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/nodejs/8.11.2-r1.1/package/usr/bin/node', '/home/matt/build/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/nodejs/8.11.2-r1.1/package/usr/bin/.debug/node']' returned non-zero exit status 1.: Traceback (most recent call last):
  File "/home/matt/build/poky/meta/lib/oe/utils.py", line 272, in run
    ret = self._target(*self._args, **self._kwargs)
  File "/home/matt/build/poky/meta/classes/package.bbclass", line 414, in splitdebuginfo
    subprocess.check_output([objcopy, '--only-keep-debug', file, debugfile], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['arm-poky-linux-gnueabi-objcopy', '--only-keep-debug', '/home/matt/build/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/nodejs/8.11.2-r1.1/package/usr/bin/node', '/home/matt/build/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/nodejs/8.11.2-r1.1/package/usr/bin/.debug/node']' returned non-zero exit status 1.


ERROR: nodejs-8.11.2-r1.1 do_package: Function failed: split_and_strip_files
ERROR: Logfile of failure stored in: /home/matt/build/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/nodejs/8.11.2-r1.1/temp/log.do_package.16903
ERROR: Task (/home/matt/build/poky/meta-nodejs/recipes-devtools/nodejs/nodejs_8.11.2.bb:do_package) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1809 tasks of which 0 didn't need to be rerun and 1 failed.


```

Any ideas what may be wrong?

**Comment by cmonr** [comment]
@MattAtkinson Looks like a NodeJS installation failure.

Mind attaching the contents of the following log?
> ERROR: Logfile of failure stored in: /home/matt/build/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/nodejs/8.11.2-r1.1/temp/log.do_package.16903

**Comment by MattAtkinson** [comment]
[log.do_package.16903.txt](https://github.com/armPelionEdge/manifest-pelion-edge/files/3320839/log.do_package.16903.txt)

**Comment by cmonr** [comment]
> I tried following the manual steps process

Hmm, out of curiosity, what step/command did this fail at? Does that command also have any logs?

Also, have you tried looking into if the docker variant of instructions migth work?

**Comment by MattAtkinson** [comment]
```
| /home/matt/build/poky/build/tmp/hosttools/ld: cannot find -lz
| /home/matt/build/poky/build/tmp/hosttools/ld: cannot find -lcrypto
| /home/matt/build/poky/build/tmp/hosttools/ld: cannot find -lssl
| collect2: error: ld returned 1 exit status
```
These were dependencies, i installed them with "sudo apt install zlib1g-dev libssl-dev". Hopefully the build will finish now...just waiting

**Comment by MattAtkinson** [comment]
```
WARNING: mbed-edge-core-rpi3-1.0-r0 do_fetch: Failed to fetch URL file://update_default_resources.c, attempting MIRRORS if available
ERROR: mbed-edge-core-rpi3-1.0-r0 do_fetch: Fetcher failure: Unable to find file file://update_default_resources.c anywhere. The paths that were searched were:
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/rpi3/poky
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/poky
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3-1.0/poky
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3/poky
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/poky
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/rpi3/raspberrypi3
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/raspberrypi3
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3-1.0/raspberrypi3
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3/raspberrypi3
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/raspberrypi3
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/rpi3/armv7ve
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/armv7ve
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3-1.0/armv7ve
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3/armv7ve
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/armv7ve
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/rpi3/rpi
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/rpi
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3-1.0/rpi
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3/rpi
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/rpi
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/rpi3/arm
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/arm
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3-1.0/arm
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3/arm
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/arm
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/rpi3/
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3-1.0/
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3/
    /home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/files/
    /home/matt/build/poky/build/downloads
ERROR: mbed-edge-core-rpi3-1.0-r0 do_fetch: Fetcher failure for URL: 'file://update_default_resources.c'. Unable to fetch URL from any source.
ERROR: mbed-edge-core-rpi3-1.0-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/matt/build/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/mbed-edge-core-rpi3/1.0-r0/temp/log.do_fetch.20930
ERROR: Task (/home/matt/build/poky/meta-pelion-edge/recipes-wigwag/mbed-edge-core/mbed-edge-core-rpi3.bb:do_fetch) failed with exit code '1'
```
I don't have this file. Do I need to generate it somehow?

**Comment by cmonr** [comment]
Ah, found where it was introduced: https://github.com/armPelionEdge/build-pelion-edge/commit/65247f5dd9491be574f083dc2c542c8fa69862be

@costanic Would you mind updating the documentation in this repo to reflect the new file requirement? (Thanks for the detailed commit)

@MattAtkinson Please give the referenced commit instructions a try.

**Comment by costanic** [comment]
This has already been fixed on the dev branch, so should be available on master during the next release.

**Comment by cmonr** [comment]
Closing. @MattAtkinson if switching branches doesn't fix the issue, feel free to reopen the issue.
